# Generated by Django 6.0.4 on 2026-04-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasdevice',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
