# Generated by Django 6.0.4 on 2026-04-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_gasdevice_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasdevice',
            name='current_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gasdevice',
            name='full_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gasdevice',
            name='gross_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetrylog',
            name='current_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
