# Generated by Django 6.0.4 on 2026-04-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_gasdevice_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasdevice',
            name='alert_email',
            field=models.EmailField(blank=True, help_text='Email of the security center', max_length=255, null=True),
        ),
    ]
