# Generated by Django 6.0.4 on 2026-04-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_gasdevice_alert_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasdevice',
            name='last_rebook_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
