# Generated by Django 6.0.4 on 2026-04-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_gasdevice_last_rebook_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasdevice',
            name='average_duration_days',
            field=models.IntegerField(default=40, help_text='Average days a full tank lasts'),
        ),
    ]
